In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

In [2]:
from sklearn.datasets import load_digits
digit = load_digits()

In [3]:
dir(digit)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [46]:
from sklearn.model_selection import train_test_split
train_X,test_X,train_Y,test_Y = train_test_split(digit.data,digit.target,test_size=0.2)

In [47]:
model_lr = LogisticRegression(max_iter=5000)
model_lr.fit(train_X,train_Y)
model_lr.score(test_X,test_Y)

0.9666666666666667

In [48]:
model_svc = SVC(C=10)
model_svc.fit(train_X,train_Y)
model_svc.score(test_X,test_Y)

0.9888888888888889

In [49]:
model_rf = RandomForestClassifier(n_estimators=10)
model_rf.fit(train_X,train_Y)
model_rf.score(test_X,test_Y)


0.95

In [50]:
model_dt = DecisionTreeClassifier()
model_dt.fit(train_X,train_Y)
model_dt.score(test_X,test_Y)

0.8583333333333333

In [12]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)

In [14]:
for train_index , test_index in kf.split([0,1,2,3,4,5,6,7,8]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [15]:
from sklearn.model_selection import StratifiedKFold
fold = StratifiedKFold(n_splits=3)

In [18]:
def get_score(model,train_X,test_X,train_Y,test_Y):
    model.fit(train_X,train_Y)
    return model.score(test_X,test_Y)

In [40]:
list_lr = []
list_svc = []
list_rf = []
list_dt = []

for train_index,test_index in fold.split(digit.data,digit.target):
    train_X,test_X,train_Y,test_Y = digit.data[train_index],digit.data[test_index],digit.target[train_index],digit.target[test_index]
    list_lr.append(get_score(LogisticRegression(max_iter=5000),train_X,test_X,train_Y,test_Y))
    list_svc.append(get_score(SVC(gamma=10),train_X,test_X,train_Y,test_Y))
    list_rf.append(get_score(RandomForestClassifier(n_estimators=10),train_X,test_X,train_Y,test_Y))
    list_dt.append(get_score(DecisionTreeClassifier(),train_X,test_X,train_Y,test_Y))
    

In [41]:
list_lr

[0.9248747913188647, 0.9382303839732888, 0.9232053422370617]

In [42]:
list_svc

[0.1001669449081803, 0.1018363939899833, 0.1018363939899833]

In [43]:
list_rf

[0.8647746243739566, 0.9065108514190318, 0.9081803005008348]

In [44]:
list_dt

[0.7445742904841403, 0.8146911519198664, 0.7746243739565943]

# cross valid score

In [25]:
from sklearn.model_selection import cross_val_score

In [34]:
cross_val_score(LogisticRegression(max_iter=10000),digit.data,digit.target,cv=3)

array([0.92487479, 0.93823038, 0.92320534])

In [35]:
cross_val_score(SVC(max_iter=5000),digit.data,digit.target,cv=3)

array([0.96494157, 0.97996661, 0.96494157])

In [37]:
cross_val_score(RandomForestClassifier(n_estimators=19),digit.data,digit.target,cv=3)

array([0.92153589, 0.93489149, 0.92320534])

In [39]:
cross_val_score(DecisionTreeClassifier(),digit.data,digit.target,cv=3)

array([0.75959933, 0.81469115, 0.77295492])