In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model


In [2]:
df = pd.read_csv("insurance_data.csv")
df

age  bought_insurance
0    22                 0
1    25                 0
2    47                 1
3    52                 0
4    46                 1
5    56                 1
6    55                 0
7    60                 1
8    62                 1
9    61                 1
10   18                 0
11   28                 0
12   27                 0
13   29                 0
14   49                 1
15   55                 1
16   25                 1
17   58                 1
18   19                 0
19   18                 0
20   21                 0
21   26                 0
22   40                 1
23   45                 1
24   50                 1
25   54                 1
26   23                 0

In [19]:
from sklearn.model_selection import train_test_split
train_X,test_X,train_Y,test_Y   = train_test_split(df[['age']].values,df.bought_insurance,test_size = 0.1,random_state = 10)

In [20]:
reg = linear_model.LogisticRegression()
reg.fit(train_X,train_Y)

LogisticRegression()

In [21]:
reg.score(test_X,test_Y)

1.0

In [22]:
reg.predict([[44]])

array([1], dtype=int64)

In [23]:
reg.coef_

array([[0.12740563]])

In [24]:
reg.intercept_

array([-4.97335111])

In [26]:
reg.predict_proba(test_X)

array([[0.06470723, 0.93529277],
       [0.10327405, 0.89672595],
       [0.92775095, 0.07224905]])

# lets undestand sigmoid function in math

In [50]:
import math
def sigmoid(x):
    a = 1/(1+math.exp(x))
    return a
def get_predicted_value(x):
    a = (0.12740563*x) - 4.97335111
    z = sigmoid(a)
    return z


In [59]:
age = 39
get_predicted_value(age)

0.5011328830613683

In [62]:
reg.predict([[38]]) 

array([0], dtype=int64)

In [42]:
print(type(int(reg.coef_[0][0])))

<class 'int'>
